### ISSUE TITLE
Kafka version outdates

### ISSUE THREAD

**Issue by g-wozniak** [eirslett/kafka-please#2]
Hi!
Thank you for your work on the package. It's really helpful.
I tried to use it for automation but realised that Kafka version is outdated. It's relevant as upon connecting I am getting error as here: https://issues.apache.org/jira/browse/KAFKA-3593 . 

I amended `fetch.sh` to pull the latest Kafka: **[https://downloads.apache.org/kafka/2.5.0/kafka_2.13-2.5.0.tgz](https://downloads.apache.org/kafka/2.5.0/kafka_2.13-2.5.0.tgz)** but it seems it changed its behaviour and tests don't start anymore as the promise (healthcheck) never passes.

This package is really good, could you either pair up or help investigating the issue and try to amend it with the up-to-date Kafka? 

Thank you!

My log is:

```
STDOUT ZOOKEEPER: 2020-06-30 17:23:40 INFO  NIOServerCnxnFactory:686 - binding to port 0.0.0.0/0.0.0.0:18002
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:40 INFO  ZKDatabase:117 - zookeeper.snapshotSizeFactor = 0.33
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:40 INFO  FileTxnSnapLog:404 - Snapshotting: 0x0 to /tmp/zookeeper-780UzBdi0aGQxCH/version-2/snapshot.0
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:40 INFO  FileTxnSnapLog:404 - Snapshotting: 0x0 to /tmp/zookeeper-780UzBdi0aGQxCH/version-2/snapshot.0
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:40 INFO  ContainerManager:64 - Using checkIntervalMs=60000 maxPerMinute=10000
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:41 INFO  FourLetterCommands:234 - The list of known four letter word commands is : [{1936881266=srvr, 1937006964=stat, 2003003491=wchc, 1685417328=dump, 1668445044=crst, 1936880500=srst, 1701738089=envi, 1668247142=conf, -720899=telnet close, 2003003507=wchs, 2003003504=wchp, 1684632179=dirs, 1668247155=cons, 1835955314=mntr, 1769173615=isro, 1920298859=ruok, 1735683435=gtmk, 1937010027=stmk}]
 undefined
STDOUT ZOOKEEPER: 2020-06-30 17:23:41 INFO  FourLetterCommands:235 - The list of enabled four letter word commands is : [[srvr]]is : [[srvr]]
 undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
Now waiting for 1000 ms. undefined
```

**Comment by eirslett** [comment]
Oh I see... this package really is outdated, and I don't have the time now to look at it. What I would suggest instead, is to use [Testcontainers](https://github.com/testcontainers/testcontainers-node) to start Kafka in a Docker container. That library will handle "everything" for you (as long as you have Docker installed) in a similar way as this package.
